version: "3"
services:
  postgres:
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - /opt/postgres:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - /opt/redis:/data
    restart: always
  proxy:
    image: nginx:1.18-alpine
    ports:
      - "80:80"
    extra_hosts:
      - "host:${LOCAL_IP}"
    volumes:
      - /opt/nginx:/etc/nginx
    restart: always
