hostname: localhost
port: 9000
environment: dev
debug: true

db_hostname: localhost
db_port: 5432
db_database: ratify
db_username: ratify-be
db_password: ratify-be

domain: ratify.daystram.com
secret: secret1234
