hostname: localhost
port: 9000
environment: dev
debug: true

db_hostname: localhost
db_port: 5432
db_database: ratify
db_username: ratify-be
db_password: ratify-be

redis_hostname: localhost
redis_port: 6379
redis_password: ratify-be
redis_database: 0

smtp_server: localhost
smtp_port: 587
smtp_username: no-reply@localhost
smtp_password: ratify-be

domain: ratify.daystram.com
secret: secret1234
