{{- if .Values.ingress.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "ratify.fullname" . }}
  labels:
    {{- include "ratify.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`{{ .Values.ingress.host }}`)"
      services:
        - name: {{ include "ratify.fullname" . }}-fe
          passHostHeader: true
          port: {{ .Values.service.port }}
      middlewares:
        - name: gzip
    - kind: Rule
      match: "Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/api`)"
      services:
        - name: {{ include "ratify.fullname" . }}-be
          passHostHeader: true
          port: {{ .Values.service.port }}
    - kind: Rule
      match: "Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/oauth`)"
      services:
        - name: {{ include "ratify.fullname" . }}-be
          passHostHeader: true
          port: {{ .Values.service.port }}
      middlewares:
        - name: cors
  {{- if .Values.ingress.tls }}
  tls:
    secretName: cert-{{ include "ratify.fullname" . }}
  {{- end }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: gzip
spec:
  compress: {}

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors
spec:
  headers:
    accessControlAllowOriginList:
      - "*"
    accessControlAllowMethods:
      - "GET"
      - "POST"
    accessControlAllowHeaders:
      - "Content-Type"
      - "Content-Length"
      - "Authorization"
      - "Origin"
    accessControlExposeHeaders:
      - "Content-Type"
      - "Content-Length"
    accessControlAllowCredentials: false
    accessControlMaxAge: 120

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cert-{{ include "ratify.fullname" . }}
spec:
  secretName: cert-{{ include "ratify.fullname" . }}
  dnsNames:
    - {{ .Values.ingress.host }}
  issuerRef:
    kind: {{ .Values.ingress.certificate.issuerRef.kind }}
    name: {{ .Values.ingress.certificate.issuerRef.name }}
{{- end }}
