name: Build

on: push

jobs:
  lint-fe:
    name: Lint ratify-fe
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ratify-fe
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: yarn install
      - name: eslint
        run: yarn lint
  build-fe:
    name: Build ratify-fe
    runs-on: Ubuntu-20.04
    defaults:
      run:
        working-directory: ratify-fe
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: yarn install
      - name: Provide Env File
        run: echo $FE_ENV_FILE > .env.production
      - name: Build
        run: yarn build
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-fe
          path: |
            ratify-fe/dist/
  lint-be:
    name: Lint ratify-be
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: ratify-be
  build-be:
    name: Build ratify-be
    runs-on: Ubuntu-20.04
    container: daystram/go-builder:1.15
    defaults:
      run:
        working-directory: ratify-be
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          swag init
          go mod tidy
      - name: Build
        run: go build -a -o app .
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-be
          path: |
            ratify-be/app
            ratify-be/docs/swagger.json
